require('configs/completion')
require('configs/lspconfig')
require('configs/lspkind')
require('configs/telescope')
require('configs/lualine')
require('configs/neoscroll')
require('configs/nvim-tree')
require('configs/vim-floaterm')
